# Basic introduction to NumPy

**Why numpy?** Numpy stands for *numerical python* and is highly optimized (and then fast) for computations in python. Numpy is one of the core package on which many others are based on, such as scipy (for *scientific python*), matplotlib or pandas (described at the end of this chapter). A lot of other scientific tools are also based on numpy and that justifies to have - at least - a basic understanding of how it works. Very well, but one could also ask why using python?

**Why python?** Depending on your preferences and your purposes, python can be a very good option or not (of course this is largely a matter of taste and not everyone agrees with this statement). In any case, many tools are available in python, scanning a very broad spectrum of applications, from machine learning to web design or string processing.

## The core object: arrays

The core of numpy is the called numpy array. These objects allow to efficiently perform computations over large dataset in a very consise way from the language point of view, and very fast from the processing time point of view. The price to pay is to give up explicit *for* loops. This lead to somehow a counter intuitive logic - at first.

### Main differences with usual python lists

The first point is to differenciate numpy array from python list, since they don't behave in the same way. Let's define two python lists and the two equivalent numpy arrays.

In [2]:
import numpy as np
l1, l2 = [1, 2, 3], [3, 4, 5]
a1, a2 = np.array([1, 2, 3]), np.array([3, 4, 5])
print(l1, l2)

[1, 2, 3] [3, 4, 5]


First of all, all mathematical operations act element by element in a numpy array. For python list, the addition acts as a concatenation of the lists, and a multiplication by a scalar acts as a replication of the lists:

In [3]:
# obj1+obj2
print('python lists: {}'.format(l1+l2))
print('numpy arrays: {}'.format(a1+a2))

python lists: [1, 2, 3, 3, 4, 5]
numpy arrays: [4 6 8]


In [3]:
# obj*3
print('python list: {}'.format(l1*3))
print('numpy array: {}'.format(a1*3))

python list: [1, 2, 3, 1, 2, 3, 1, 2, 3]
numpy array: [3 6 9]


One other important difference is about the way to access element of an array, the so called slicing and indexing. Here the behaviour of python list and numpy arrays are closer expect that numpy array supports few more features, such as indexing by an array of integer (which doesn't work for python lists). Use cases of such indexing will be heavily illustrated in the next chapters.

In [4]:
# Indexing with an integer: obj[1]
print('python list: {}'.format(l1[1]))
print('numpy array: {}'.format(a1[1]))

python list: 2
numpy array: 2


In [5]:
# Indexing with a slicing: obj[slice(1,3))]
print('python list: {}'.format(l1[slice(1,3)]))
print('numpy array: {}'.format(l1[slice(1,3)]))

python list: [2, 3]
numpy array: [2, 3]


In [6]:
# Indexing with a list of integers: obj[[0,2]]
print('python list: IMPOSSIBLE')
print('numpy array: {}'.format(a1[[0,2]]))

python list: IMPOSSIBLE
numpy array: [1 3]


### Main caracteristics of an array

The strenght of numpy array is to be multidimensional. This enables a description of a whole complex dataset into a single numpy array, on which one can do operations. In numpy, dimension are also called *axis*. For example, a set of 2 position in space $\vec{r}_i$ can be seen as 2D numpy array, with the first axis being the point $i=1$ or $i=2$, and the second axis being the coordinates ($x,y,z$). There are few attributes which describe multidimentional arrays:

  + `a.dtype`: type of data contained in the array
  + `a.shape`: number of elements along each dimension (or axis)
  + `a.size`: total number of elements (product of `a.shape` elements)
  + `a.ndim`: number of dimensions (or axis)

In [7]:
points = np.array([[ 0,  1, 2],
                   [ 3,  4, 5]])

print('a.dtype = {}'.format(points.dtype))
print('a.shape = {}'.format(points.shape))
print('a.size  = {}'.format(points.size))
print('a.ndim  = {}'.format(points.ndim))

a.dtype = int32
a.shape = (2, 3)
a.size  = 6
a.ndim  = 2


## The three key features of NumPy

### Vectorization

The *vectorization* is a way to make computations on numpy array **without explicit loops**, which are very slow in python. The idea of vectorization is to compute a given operation *element-wise* while the operation is called on the array itself. An example is given below to compute the inverse of 100000 numbers, both with explicit loop and vectorization.

In [8]:
a = np.random.randint(low=1, high=100, size=100000)

def explicit_loop_for_inverse(array):
    res = []
    for a in array:
        res.append(1./a)
    return np.array(res)

In [9]:
# Using explicit loop
%timeit explicit_loop_for_inverse(a)

333 ms ± 39.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
# Using list comprehension
%timeit [1./x for x in a]

263 ms ± 3.44 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
# Using vectorization
%timeit 1./a

399 µs ± 31.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**The suppression of explicit *for* loops is probably the most unfamiliar aspect of numpy - according to me - and deserves a bit a of practice. At the end, lines of codes becomes relatively short but ones need to properly think how to implement a given computation in a *pythonic way*.**

Many standard functions are implemented in a vectorized way, they are call the *universal functions*, or `ufunc`. Few examples are given below but the full description can be found in [numpy documentation](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html).

In [12]:
a = np.random.randint(low=1, high=100, size=3)
print('a        : {}'.format(a))
print('a^2      : {}'.format(a**2))
print('a/(1-a^a): {}'.format(a/(1-a**a)))
print('cos(a)   : {}'.format(np.cos(a)))
print('exp(a)   : {}'.format(np.exp(a)))

a        : [31 85 75]
a^2      : [ 961 7225 5625]
a/(1-a^a): [1.54220888e-08 1.14707187e-07 5.98927895e-08]
cos(a)   : [ 0.91474236 -0.98437664  0.92175127]
exp(a)   : [2.90488497e+13 8.22301271e+36 3.73324200e+32]


All these ufunct can work for n-dimension arrays and can be used in a very flexible way depeding on the axis you are refering too. Indeed the mathematical operation can be performed over a different axis of the array, having a totally different meaning. Let's give a simple concrete example with a 2D array of shape (5,2), *i.e.* 5 vectors of three coordinates $(x,y,z)$  Much more examples will be discussed in the section 2.

In [13]:
# Generate 5 vectors (x,y,z)
positions = np.random.randint(low=1, high=100, size=(5, 3))

# Average of the coordinate over the 5 observations
pos_mean = np.mean(positions, axis=0)
print('mean = {}'.format(pos_mean))

# Distance to the origin sqrt(x^2 + y^2 + z^2) for the 5 observations
distances = np.sqrt(np.sum(positions**2, axis=1))
print('distances = {}'.format(distances))

mean = [53. 53. 55.]
distances = [ 45.88027899 123.13001259 118.77289253 126.09123681  86.18004409]


**Note on matrix product.** Numpy arrays can be used to describe and manipulate matrices. There is a special way to do a matrix product instead of element-wise product. You can use `np.dot(a, b)` (or `a.dot(b)`), even if several other syntaxes are possible (like `a@b`, or equivalently `np.matmul(a, b)`). If you are interested into these features, I would recommand to read in detail the [`np.dot` documentation](https://numpy.org/devdocs/reference/generated/numpy.dot.html), because different syntax dont really correspond to the same mathematical operation (for instance, `np.matmul(a, b)` allows *broadcasting* for $2 \times 2$ matrix product - cf. latter).

In [24]:
a = np.array([[1, 1],
              [1, 0]], dtype=np.int)

b = np.array([[2, 4],
              [1, 1]], dtype=np.int)

print(np.dot(a, b))

[[3 5]
 [2 4]]


### Broadcasting

The *broadcasting* is a way to compute operation between arrays of having different sizes in a implicit (and consice) manner. One concrete example could be to translate three positions $\vec{r}_i=(x,y)_i$ by a vector $\vec{d}_0$ simply by adding `points+d0` where `points.shape=(3,2)` and `d0.shape=(2,)`. Few examples are given below but more details are give in [this documentation](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).

In [14]:
# operation between shape (3) and (1)
a = np.array([1, 2, 3])
b = np.array([5])
print('a+b = \n{}'.format(a+b))

a+b = 
[6 7 8]


In [15]:
# operation between shape (3) and (1,2)
a = np.array([1, 2, 3])
b = np.array([
              [4],
              [5],
             ])
print('a+b = \n{}'.format(a+b))

a+b = 
[[5 6 7]
 [6 7 8]]


In [16]:
# Translating 3 2D vectors by d0=(1,4)
points = np.random.normal(size=(3, 2))
d0 = np.array([1, 4])
print('points:\n {}\n'.format(points))
print('points+d0:\n {}'.format(points+d0))

points:
 [[ 0.55667403 -0.78854994]
 [ 2.6426123   1.5324207 ]
 [-0.73453837  0.81005631]]

points+d0:
 [[1.55667403 3.21145006]
 [3.6426123  5.5324207 ]
 [0.26546163 4.81005631]]


Not all shapes can be combined together and there are *broadcasting rules*, which are (quoting the [numpy documentation](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)):

> When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when
> 
>   1. they are equal, or
>   2. one of them is 1
  
In a failing case, one can then add a new *empty axis* `np.newaxis` to an array to make their dimension equal and then the broadcasting possible. Here is a very simle example:

In [17]:
a = np.arange(10).reshape(2,5)
b = np.array([10,20])

In [18]:
try:
    res = a+b
    print('Possible for {} and {}:'.format(a.shape, b.shape))
    print('a+b = \n {}'.format(res))
except ValueError:
    print('Impossible for {} and {}'.format(a.shape, b.shape))

Impossible for (2, 5) and (2,)


In [19]:
c = b[:, np.newaxis]
try: 
    res = a+c
    print('Possible for {} and {}:'.format(a.shape, c.shape))
    print('a+c = \n {}'.format(res))
except ValueError:
    print('Broadcasting for {} and {}'.format(a.shape, c.shape))

Possible for (2, 5) and (2, 1):
a+c = 
 [[10 11 12 13 14]
 [25 26 27 28 29]]


### Working with sub-arrays: slicing, indexing and mask (or selection)

As mentioned eariler, *slicing and indexing* are ways to access elements or sub-arrays in a smart way. Python allows slicing with `Slice()` object but `numpy` allows to push the logic much further with what is called *fancy indexing*. Few examples are given below and for more details, please have a look to [this documentation page](https://docs.scipy.org/doc/numpy-1.15.1/reference/arrays.indexing.html).

**Rule 1:** the syntax is `a[i]` to access the ith element. It is also possible to go from the last element using negative indices: `a[-1]` is the last element.

In [20]:
a = np.random.randint(low=1, high=100, size=10)
print('a = {}'.format(a))
print('a[2] = {}'.format(a[2]))
print('a[-1] = {}'.format(a[-1]))
print('a[[1, 2, 5]] = {}'.format(a[[1, 2, 5]]))

a = [98 93 61 78 48 93 47  7 43 31]
a[2] = 61
a[-1] = 31
a[[1, 2, 5]] = [93 61 93]


**Rule 2:** numpy also support array of indices. If the index array is multi-dimensional, the returned array will have the same dimension as the indices array.

In [21]:
# Small n-dimensional indices array: 3 arrays of 2 elements
indices = np.arange(6).reshape(3,2)
print('indices =\n {}'.format(indices))
print('a[indices] =\n {}'.format(a[indices]))

indices =
 [[0 1]
 [2 3]
 [4 5]]
a[indices] =
 [[98 93]
 [61 78]
 [48 93]]


In [22]:
# Playing with n-dimensional indices array: 2 arrays of (10, 10) arrays
indices_big = np.random.randint(low=0, high=10, size=(2, 3, 2))
print('indices_big =\n {}'.format(indices_big))
print('a[indices_big] =\n {}'.format(a[indices_big]))

indices_big =
 [[[3 5]
  [7 9]
  [1 9]]

 [[6 4]
  [7 9]
  [2 1]]]
a[indices_big] =
 [[[78 93]
  [ 7 31]
  [93 31]]

 [[47 48]
  [ 7 31]
  [61 93]]]


**Rule 3:** There is a smart way to access sub-arrays with the syntax `a[min:max:step]`. In that way, it's for example very easy to take one element over two (`step=2`), or reverse the order of an array (`step=-1`). This syntax works also for n-dimensional array, where each dimension is sperated by a comma. An example is given for a 1D array and for a 3D array of shape (5, 2, 3) - that can considered as 5 observations of 2 positions in space.

In [23]:
# 1D array
a = np.random.randint(low=1, high=100, size=10)
print('full array a              = {}'.format(a))
print('from 0 to 1: a[:2]        = {}'.format(a[:2]))
print('from 4 to end: a[4:]      = {}'.format(a[4:]))
print('reverse order: a[::-1]    = {}'.format(a[::-1]))
print('all even elements: a[::2] = {}'.format(a[::2]))

full array a              = [71 51 35  3  9 27 68 24 25 98]
from 0 to 1: a[:2]        = [71 51]
from 4 to end: a[4:]      = [ 9 27 68 24 25 98]
reverse order: a[::-1]    = [98 25 24 68 27  9  3 35 51 71]
all even elements: a[::2] = [71 35  9 68 25]


In [24]:
# 3D array
a = np.random.randint(low=0, high=100, size=(5, 2, 3))
print('a = \n{}'.format(a))

a = 
[[[45 26 15]
  [47 86 38]]

 [[98 11 61]
  [26 81 26]]

 [[15 53 25]
  [66  2 10]]

 [[96 22 88]
  [90 36 17]]

 [[69 35 54]
  [ 2 22 90]]]


Let's say, one wants to take only the $(x,y)$ coordinates for the first vector for all 5 observations. This is how each axis will be sliced:
  - first axis (=5 observations): `:`, *i.e.* takes all
  - second axis (=2 vectors): `1` *i.e.* only the 2nd element
  - third axis (=3 coordinates): `0:2` *i.e.* from $0$ to $2-1=1$, so only $(x,y)$

In [25]:
# Taking only the x,y values of the first vector for all observation:
print('a[:, 0, 0:2] =\n {}'.format(a[:, 0, 0:2]))

a[:, 0, 0:2] =
 [[45 26]
 [98 11]
 [15 53]
 [96 22]
 [69 35]]


In [26]:
# Reverse the order of the 2 vector for each observation:
print('a[:, ::-1, :] = \n{}'.format(a[:, ::-1, :]))

a[:, ::-1, :] = 
[[[47 86 38]
  [45 26 15]]

 [[26 81 26]
  [98 11 61]]

 [[66  2 10]
  [15 53 25]]

 [[90 36 17]
  [96 22 88]]

 [[ 2 22 90]
  [69 35 54]]]


**Rule 4:** The last part of of indexing is about *masking* array or in a more common language, *selecting* sub-arrays/elements. This allows to get only elements satisfying a given criteria, exploiting the indexing rules described above. Indeed, a boolean operation applied to an array such as `a>0` will directly return an array of boolean values `True` or `False` depending if the corresponding element satisfies the condition or not.

In [27]:
a = np.random.randint(low=-100, high=100, size=(5, 3))
mask = a>0
print('a = \n{}'.format(a))
print('\nmask = \n {}'.format(mask))

a = 
[[  94  -73    3]
 [-100   89   47]
 [  47  -65  -53]
 [ -35 -100  -21]
 [ -65  -63  -23]]

mask = 
 [[ True False  True]
 [False  True  True]
 [ True False False]
 [False False False]
 [False False False]]


In [28]:
print('\na[mask] = \n {}'.format(a[mask])) # always return 1D array
print('\na*mask = \n {}'.format(a*mask)) # preserves the dimension (False=0)
print('\na[~mask] = \n {}'.format(a[~mask])) # ~mask is the negation of mask
print('\na*~mask  = \n {}'.format(a*~mask)) # working for a product too.


a[mask] = 
 [94  3 89 47 47]

a*mask = 
 [[94  0  3]
 [ 0 89 47]
 [47  0  0]
 [ 0  0  0]
 [ 0  0  0]]

a[~mask] = 
 [ -73 -100  -65  -53  -35 -100  -21  -65  -63  -23]

a*~mask  = 
 [[   0  -73    0]
 [-100    0    0]
 [   0  -65  -53]
 [ -35 -100  -21]
 [ -65  -63  -23]]


**Note** the case of boolean arrays as indices has then a special treatment in numpy (since the result is always a 1D array). There is actually a dedicated numpy object called *masked array* (cf. [documentation](https://docs.scipy.org/doc/numpy-1.15.1/reference/maskedarray.html)) which allows to keep the whole array but without considering some elements in the computation (*e.g.* CCD camera with dead pixel). Note however that when a boolean array is used in an mathematical operation (such as `a*mask`) then `False` is treated as `0` and `True` as `1`:

In [29]:
print('a+mask = \n{}'.format(a+mask))

a+mask = 
[[  95  -73    4]
 [-100   90   48]
 [  48  -65  -53]
 [ -35 -100  -21]
 [ -65  -63  -23]]


This boolean arrays are also very useful to *replace a category of elements* with a given value in a very easy, consise and readable way:

In [30]:
a = np.random.randint(low=-100, high=100, size=(5, 3))
print('Before: a=\n{}'.format(a))

a[a<0] = a[a<0]**2
print('\nAfter: a=\n{}'.format(a))

Before: a=
[[-16  76  19]
 [ 23 -25  75]
 [-70 -38  35]
 [ 61 -13 -72]
 [ 60  40  93]]

After: a=
[[ 256   76   19]
 [  23  625   75]
 [4900 1444   35]
 [  61  169 5184]
 [  60   40   93]]


## Few useful NumPy tips

This short section is presenting few handy features to know about NumPy, which can help beginners. For a slightly more complete view of "everyday NumPy", I would recommand to have a look to the [*cheat sheet* from DataCamp](https://www.datacamp.com/community/blog/python-numpy-cheat-sheet).

### Dummy array initialization

In [6]:
x = np.zeros(shape=(3, 2))               # Only 0
x = np.ones(shape=(3, 2))                # Only 1
x = np.full(shape=(3, 2), fill_value=10) # Only 10
x = np.eye(2)                            # Create identity matrix (only return 2D array)

### Create sequence of numbers

In [126]:
# Linear inteveral from 0 to 10
x = np.linspace(0, 10, 10) # 10 numbers between 0 and 1
x = np.arange(0, 10, 1.0)  # One number every 1.0 between 0 and 1
x = np.logspace(0, 10, 10) # 10 numbers between 10**0 and 10**10

### Shape-based manipulation of arrays

In [127]:
a = np.arange(0, 18).reshape(3, 3, 2)
x = a.ravel()                     # Return a flat array
x = a.reshape(9, 2)               # change the shape
x = a.T                           # transpose array: a.T[i, j, k] = a[k, j, i]
x = np.concatenate([a,a], axis=0) # concatenate arrays along a given axis (new shape is (6, 3, 2))
x = np.stack([a, a], axis=0)      # group arrays along a given axis (new dim is (2, 3, 3, 2))

### Compare arrays

In [128]:
# Making dummy arrays for comparisons
a = np.arange(-6, 6).reshape(3, 4)
b = np.abs(a)
c = np.append(b, [[1, 2, 3, 4]], axis=0)

# Print the arrays
print('a = {}\n'.format(a))
print('b = {}\n'.format(b))
print('c = {}'.format(c))

a = [[-6 -5 -4 -3]
 [-2 -1  0  1]
 [ 2  3  4  5]]

b = [[6 5 4 3]
 [2 1 0 1]
 [2 3 4 5]]

c = [[6 5 4 3]
 [2 1 0 1]
 [2 3 4 5]
 [1 2 3 4]]


In [129]:
# Arrays with the same shapes
print(np.equal(a, b))             # Return array with element-wise True/False (exactly equivalent to x = a==b)
print(np.all(a==b))               # Return true is all element is true
print(np.allclose(a, b, rtol=10)) # same as all function with relative/absolute numerical precision
print(np.any(a==b))               # Return true if any of the element is true

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
False
True
True


In [130]:
# Arrays with the possibly different shapes
print(np.array_equal(a, c)) # Return True if a and b have the same shape and are equal element-wise
print(np.array_equiv(a, b)) # Return True if a and b have consistent shape (braodcasting) and same elements

False
False


In [131]:
# Example of equivalent arrays
a = np.array([1, 2])
b = np.array([[1, 2], [1, 2]])
np.array_equiv(a, b)

True