# f-strings and formatting

In [5]:
a =  "hello my name is' Louie and I am' 35 years old"

In [6]:
print(a)

hello my name is' Louie and I am' 35 years old


In [9]:
age =35.567656755

In [10]:
text =   "hello my name is' Louie and I am'"+ str(age)+" years old"

print(text)

hello my name is' Louie and I am'35.567656755 years old


In [11]:
ftext = f"hello my name is Louie and I am {age} years old"
print(ftext)

hello my name is Louie and I am 35.567656755 years old


In [12]:
old_text = "hello my name is Louie and I am {} years old".format(age)
print(old_text)

hello my name is Louie and I am 35.567656755 years old


In [13]:
ftext = f"hello my name is Louie and I am {age*0.75} years old"
print(ftext)

hello my name is Louie and I am 26.67574256625 years old


In [17]:
ftext = f"hello my name is Louie and I am {age*0.75:.3f} years old"
print(ftext)

hello my name is Louie and I am 26.676 years old


In [18]:
ftext = f"hello my name is Louie and I am {age*0.75:.3e} years old"
print(ftext)

hello my name is Louie and I am 2.668e+01 years old


In [19]:
ages = { 'louie' : 35.67, 'paul' : 22.345, 'mathusela': 10000.4554}
for name, age in ages.items():
    print (f'The person called {name} is {age:.1f} years old')

The person called louie is 35.7 years old
The person called paul is 22.3 years old
The person called mathusela is 10000.5 years old


In [20]:
ages = { 'louie' : 35.67, 'paul' : 22.345, 'mathusela': 10000.4554}
for name in ages.keys():
    print (f'The person called {name} is {ages[name]:.1f} years old')

The person called louie is 35.7 years old
The person called paul is 22.3 years old
The person called mathusela is 10000.5 years old


In [21]:

ages = { 'louie' : 35.67, 'paul' : 22.345, 'mathusela': 10000.4554}
for name, age in ages.items():
    print ('The person called', name, ' is ', age , 'years old')

The person called louie  is  35.67 years old
The person called paul  is  22.345 years old
The person called mathusela  is  10000.4554 years old


# Broadcasting

In [22]:
# broadcasting is a property of numpy arrays
import numpy as np

In [23]:
a = np.random.normal(36, 2, size = 3000)

In [24]:
a

array([34.98050968, 37.26720656, 34.78348677, ..., 35.10152186,
       37.51629516, 32.71685957])

In [25]:
b = a.reshape(3, 1000)

In [26]:
# we could also just have done a = np.random.normal(36, 2, size = (3, 1000))

In [27]:
b.shape

(3, 1000)

In [28]:
b

array([[34.98050968, 37.26720656, 34.78348677, ..., 34.55724471,
        34.491503  , 36.76070393],
       [34.40783679, 31.88271342, 35.24772744, ..., 34.39812702,
        35.5554054 , 34.83143645],
       [36.73182406, 32.79835592, 35.80751577, ..., 35.10152186,
        37.51629516, 32.71685957]])

In [33]:
b =b.reshape(1000,3)

TypeError: unsupported format string passed to numpy.ndarray.__format__

In [34]:
b.shape

(1000, 3)

In [35]:
b

array([[34.98050968, 37.26720656, 34.78348677],
       [38.67478327, 38.47181361, 38.3028491 ],
       [41.65525644, 34.85450403, 35.7227854 ],
       ...,
       [34.75997115, 37.61518157, 36.96451047],
       [35.91117678, 34.10647957, 37.8768459 ],
       [35.10152186, 37.51629516, 32.71685957]])

In [36]:
c = np.array([1,10,100])

In [37]:
b * c

array([[  34.98050968,  372.67206564, 3478.34867687],
       [  38.67478327,  384.71813613, 3830.28491034],
       [  41.65525644,  348.54504034, 3572.27853982],
       ...,
       [  34.75997115,  376.15181566, 3696.45104742],
       [  35.91117678,  341.06479571, 3787.68458956],
       [  35.10152186,  375.16295156, 3271.68595661]])

In [38]:
b.shape

(1000, 3)

In [39]:
c.shape

(3,)

In [46]:
d = np.random.normal(36, 2, size = ( 10, 2, 5))

In [47]:
d *c

ValueError: operands could not be broadcast together with shapes (10,2,5) (3,) 

In [48]:
c = np.random.normal (2, 5, size=5)

In [49]:
c

array([ 0.10841669,  6.54376802,  1.74518212,  3.76889145, -3.18224877])

In [50]:
d * c

array([[[   3.94479202,  236.63212741,   59.02661591,  128.98178181,
         -109.8054096 ],
        [   3.90987651,  246.11575262,   60.97663425,  132.79819283,
         -108.70519859]],

       [[   3.76929155,  228.13881481,   59.08992863,  135.83582556,
         -118.82458064],
        [   3.84429898,  228.1658606 ,   60.8619581 ,  127.74976788,
         -114.4432277 ]],

       [[   3.86814439,  219.51351539,   59.17864528,  137.11982223,
         -110.53905972],
        [   3.6804642 ,  223.91987321,   63.7493633 ,  130.07611492,
         -107.22187194]],

       [[   3.6388048 ,  247.85481905,   55.6646882 ,  125.74703773,
         -130.70832296],
        [   3.79594619,  238.9924383 ,   63.53052839,  145.01347355,
         -111.31713445]],

       [[   3.86870507,  240.11002197,   61.45067729,  115.54720232,
         -104.62468133],
        [   3.96133426,  217.28502117,   66.02978287,  128.99689543,
         -111.55292591]],

       [[   3.85172117,  240.07790241,   64.219817

In [51]:
c = np.random.normal (2, 5, size=(5,6))

In [52]:
c

array([[ 2.18342114,  5.04228184,  9.6233072 , -1.09656287, -8.71857063,
        10.56590991],
       [-8.947787  ,  9.22486028,  1.60141276,  8.93701119,  6.87107277,
        11.78265802],
       [-0.07019375,  0.56411712, -2.47070293,  1.58964048, -3.85525666,
        -0.30264802],
       [ 2.91196084,  2.78114219, -0.61805164,  7.23771885,  4.83043151,
        -0.21513066],
       [ 3.4327351 ,  5.83521997, 12.02813091,  1.44917052, -5.61924442,
        12.34031758]])

In [53]:
print (f' d is oh shape {d.shape}, c is of shape {c.shape}')

 d is oh shape (10, 2, 5), c is of shape (5, 6)


In [54]:
d * c

ValueError: operands could not be broadcast together with shapes (10,2,5) (5,6) 

In [55]:
c = np.random.normal (2, 5, size=(2,5))

In [56]:
print (f' d is oh shape {d.shape}, c is of shape {c.shape}')

 d is oh shape (10, 2, 5), c is of shape (2, 5)


In [57]:
d*c

array([[[  73.36313608,   -6.95862724,  -65.54071841,  392.64096848,
           54.553801  ],
        [ -33.6907553 ,   50.64297151,  246.18726924, -133.49074924,
          161.0285944 ]],

       [[  70.09927216,   -6.70886489,  -65.61101824,  413.50576301,
           59.03472834],
        [ -33.12568458,   46.94944169,  245.72427534, -128.41599623,
          169.52852609]],

       [[  71.9376844 ,   -6.45522121,  -65.70952555,  417.41445221,
           54.9182949 ],
        [ -31.71394753,   46.07574947,  257.38189485, -130.75447542,
          158.83129373]],

       [[  67.67254916,   -7.28865228,  -61.80777262,  382.79389527,
           64.93883922],
        [ -32.70903664,   49.17721485,  256.49837004, -145.76973393,
          164.8977411 ]],

       [[  71.94811163,   -7.06090148,  -68.23229613,  351.74398111,
           51.97989849],
        [ -34.13415814,   44.71050316,  266.58886854, -129.66962769,
          165.24702676]],

       [[  71.63225423,   -7.05995694,  -71.307035

In [59]:
a1 = np.random.normal (3, 4, size = (5, 6, 7, 8))
a2 = np.random.normal (3, 4, size = (6, 7, 8))

In [60]:
a1 + a2

array([[[[ 1.33580611e+01, -1.05588499e+01,  1.26755185e+00, ...,
           6.33057932e+00, -1.75257270e-01,  2.76754877e+00],
         [ 6.81250896e-01,  3.37845571e+00,  5.91380513e+00, ...,
           2.63586692e-01,  8.98606814e+00,  1.25737878e+01],
         [ 7.76516290e+00,  1.29460770e+00,  1.25389918e+01, ...,
           1.57910670e+00,  8.81422825e+00,  7.66586760e+00],
         ...,
         [ 1.31083064e+01,  2.66724430e+00,  3.43636938e+00, ...,
          -3.13036750e+00,  1.29598986e+01,  1.88074099e+00],
         [-6.26146754e+00,  1.21841606e+01,  8.89551259e-01, ...,
           1.23278701e+01,  7.98244648e+00,  7.93204573e+00],
         [ 8.77177496e+00,  4.27931226e+00,  6.81986642e+00, ...,
           1.72527398e+01, -2.27959525e+00, -6.81033456e-01]],

        [[ 1.00797623e+01,  6.27045879e+00,  5.89445869e+00, ...,
           2.52377029e+00,  7.98495102e+00,  7.52307503e+00],
         [ 8.87623525e+00,  3.58911536e+00,  2.42270404e+00, ...,
           1.54395752e

In [65]:
a1.mean(axis=1).shape

(5, 7, 8)

In [66]:
a1.shape

(5, 6, 7, 8)

# pandas

In [68]:
import pandas as pd

In [70]:

df = pd.read_csv('wave_data.csv')

In [71]:
df.head(10)

index              date  height  heightMax  period  energy  direction  \
0      1  01/01/2017 00:00 -99.900     -99.90 -99.900 -99.900      -99.9   
1      2  01/01/2017 00:30   0.875       1.39   4.421   4.506      -99.9   
2      3  01/01/2017 01:00   0.763       1.15   4.520   5.513       49.0   
3      4  01/01/2017 01:30   0.770       1.41   4.582   5.647       75.0   
4      5  01/01/2017 02:00   0.747       1.16   4.515   5.083       91.0   
5      6  01/01/2017 02:30   0.718       1.61   4.614   6.181       68.0   
6      7  01/01/2017 03:00   0.707       1.34   4.568   4.705       73.0   
7      8  01/01/2017 03:30   0.729       1.21   4.786   4.484       63.0   
8      9  01/01/2017 04:00   0.733       1.20   4.897   5.042       68.0   
9     10  01/01/2017 04:30   0.711       1.29   5.019   8.439       66.0   

   temperature  
0       -99.90  
1       -99.90  
2        25.65  
3        25.50  
4        25.45  
5        25.45  
6        25.50  
7        25.50  
8        25.50  
9        25.50

In [79]:
df1 = df[['direction','energy']]

In [80]:
df1[ df1 > -99].fillna(0)

direction  energy
0         0.0   0.000
1         0.0   4.506
2        49.0   5.513
3        75.0   5.647
4        91.0   5.083
5        68.0   6.181
6        73.0   4.705
7        63.0   4.484
8        68.0   5.042
9        66.0   8.439
10       64.0   4.584
11       56.0   5.211
12       67.0   5.813
13       81.0   4.710
14       90.0   5.353
15       67.0   7.436
16       90.0   6.001
17       90.0   6.414
18       88.0   6.691
19       88.0   6.804
20      122.0   6.641
21       91.0   5.958
22       92.0   6.691

In [83]:
df1.count()

direction    23
energy       23
dtype: int64

In [86]:
df1[ df1 > -99]

direction  energy
0         NaN     NaN
1         NaN   4.506
2        49.0   5.513
3        75.0   5.647
4        91.0   5.083
5        68.0   6.181
6        73.0   4.705
7        63.0   4.484
8        68.0   5.042
9        66.0   8.439
10       64.0   4.584
11       56.0   5.211
12       67.0   5.813
13       81.0   4.710
14       90.0   5.353
15       67.0   7.436
16       90.0   6.001
17       90.0   6.414
18       88.0   6.691
19       88.0   6.804
20      122.0   6.641
21       91.0   5.958
22       92.0   6.691

In [87]:
df1[ df1 > -99].count()

direction    21
energy       22
dtype: int64

In [88]:
df1 > -99

direction  energy
0       False   False
1       False    True
2        True    True
3        True    True
4        True    True
5        True    True
6        True    True
7        True    True
8        True    True
9        True    True
10       True    True
11       True    True
12       True    True
13       True    True
14       True    True
15       True    True
16       True    True
17       True    True
18       True    True
19       True    True
20       True    True
21       True    True
22       True    True

In [89]:
df1['direction']

0     -99.9
1     -99.9
2      49.0
3      75.0
4      91.0
5      68.0
6      73.0
7      63.0
8      68.0
9      66.0
10     64.0
11     56.0
12     67.0
13     81.0
14     90.0
15     67.0
16     90.0
17     90.0
18     88.0
19     88.0
20    122.0
21     91.0
22     92.0
Name: direction, dtype: float64

In [92]:
df1.direction.mean()

62.573913043478264

In [93]:
df1.direction.std()

53.64048858661036

# slicing with arrays

In [94]:
a = np.random.normal(4,5, size=10)

In [95]:
a

array([-3.65443963,  4.25242979,  7.57810559,  1.25345273,  6.73349597,
        0.8002761 , -1.70099848,  2.55246923, -1.15530607,  0.74970881])

In [96]:
a[5]

0.8002761036734967

In [97]:
a[:]

array([-3.65443963,  4.25242979,  7.57810559,  1.25345273,  6.73349597,
        0.8002761 , -1.70099848,  2.55246923, -1.15530607,  0.74970881])

In [98]:
a[2:]

array([ 7.57810559,  1.25345273,  6.73349597,  0.8002761 , -1.70099848,
        2.55246923, -1.15530607,  0.74970881])

In [99]:
a[2:6]

array([7.57810559, 1.25345273, 6.73349597, 0.8002761 ])

In [100]:
d.shape

(10, 2, 5)

In [109]:
d[2:5, : , 5:6]

array([], shape=(3, 2, 0), dtype=float64)

In [102]:
a

array([-3.65443963,  4.25242979,  7.57810559,  1.25345273,  6.73349597,
        0.8002761 , -1.70099848,  2.55246923, -1.15530607,  0.74970881])

In [106]:
a[-3]

2.552469229284801

In [107]:
a[2:-3]

array([ 7.57810559,  1.25345273,  6.73349597,  0.8002761 , -1.70099848])

In [115]:
a[6:1:-1]

array([-1.70099848,  0.8002761 ,  6.73349597,  1.25345273,  7.57810559])