# CHALLENGE

Parts a) and b): *Open the file* `'LAssommoir_en.txt'` *and count the number of lines in the file *

In [9]:
F =open('LAssommoir_en.txt')
lines = F.readlines()
print(f'the file cobtains {len(lines)} lines')

the file cobtains 1180 lines


alternative solution...


In [11]:
F =open('LAssommoir_en.txt')
lineCounter=0
for line in F:
    lineCounter = lineCounter + 1
print(f'the file cobtains {lineCounter} lines')

the file cobtains 1180 lines


Part c) *How many words contain the letter* `q` ? 

In [14]:
F =open('LAssommoir_en.txt')
lines = F.readlines()
counter = 0
for line in lines:
  words = line.split(" ")
  for word in words:
    if "q" in word :
        counter  = counter + 1
print (f'your file has {counter} words containing the letter q')

your file has 40 words containing the letter q


Or for fun...

In [17]:
def countLetterInFile( letter, file):
    ''' 
    this function counter the number of times that a given letter occurs in a given file and returns that values
    '''
    F =open(file)
    lines = F.readlines()
    counter = 0
    for line in lines:
      words = line.split(" ")
      for word in words:
        if letter in word :
          counter  = counter + 1

    print(f'file {file} contains the letter {letter} {counter} times.')
    return counter
    

In [16]:
for file in ['LAssommoir_en.txt','LAssommoir_fr.txt','LAssommoir_it.txt','LAssommoir_es.txt','LAssommoir_de.txt']:
    countLetterInFile('q', file)

file LAssommoir_en.txt contains the letter q 40 times.
file LAssommoir_fr.txt contains the letter q 374 times.
file LAssommoir_it.txt contains the letter q 206 times.
file LAssommoir_es.txt contains the letter q 448 times.
file LAssommoir_de.txt contains the letter q 5 times.


Part d *what is the most frequently used letter*

In [24]:
F =open('LAssommoir_en.txt')
lines = F.readlines()
result = {}
for line in lines: 
    for letter in line.lower().replace(' ',''):
        if letter in result.keys():
            result[letter] += 1 # increment an existing entry
        else :
            result[letter]=1 #initialise a new key with value 1

maxLetter =0
maxOccurance =0
for letter, occurance in result.items():
    if occurance > maxOccurance :
        maxLetter = letter
        maxOccurance  =occurance
print (f' The most frequent letter to occur is {maxLetter} which was present {maxOccurance} times')

 The most frequent letter to occur is e which was present 6354 times


Part e) *Rewrite the text to a new file but re,oving all special characters and numbers*

In [102]:
name='LAssommoir_en.txt'
f_in = open(name, 'r')
f_out = open ('modified_'+name, 'w')

for line in f_in:
    newline=""
    for character in line:
        if character.isalpha() :
            newline+= character
    #newline = str([character for character in line if character.isalpha() ])
    f_out.write(newline)
f_out.close()
        
    

In [98]:
a='2'
a.isalnum()

True

Part f) *What is the mean number of letter per word ? How does it compare between the french, english, german, italian, spanish, etc... versions ?*

In [105]:
def averageLengthOfWordPerFile(file):
    '''
    This function splits a file into words and cqlculqte the length of each word before taking the mean
    '''
    result = []
    f = open(file)
    for word in f.read().split(" "):
        newword = [c for c in word if c.isalpha()]
        result.append(len(newword))
    return sum(result)/len(result)

In [107]:
for file in ['LAssommoir_en.txt','LAssommoir_fr.txt','LAssommoir_it.txt','LAssommoir_es.txt','LAssommoir_de.txt']:
   av = averageLengthOfWordPerFile(file)
   print(f'The file {file} has an average letter per word of {av:.2f}')

The file LAssommoir_en.txt has an average letter per word of 4.78
The file LAssommoir_fr.txt has an average letter per word of 4.77
The file LAssommoir_it.txt has an average letter per word of 5.48
The file LAssommoir_es.txt has an average letter per word of 4.96
The file LAssommoir_de.txt has an average letter per word of 5.48


# Numpy exerise

- a) Generate an array of three lists of 10 values, which can represent coordinates in $x$, $y$, $z$ of 10 vectors. Use `np.random.randint()`
- b) Reorganise the values to be a list of 10 $(x,y,z)$ triplets. *hint: should you reshape or transpose?*
- c) Translate all the points by a vector $(-1, -1, -1)$.
- d) Calculate the distance of each point to the origin. What is the avergae distance from the origin ? *hint: check out `np.mean()`* 
- e) BONUS: Using a mask, select only the vectors which are  less than the mean distance away from the origin.

## Solution of a)

In [26]:
import numpy as np

In [51]:
vectors = np.random.randint(-100, 100, (3,10))

In [52]:
vectors

array([[ 52, -76, -13, -85, -75,  25, -52, -98, -86, -88],
       [ -9, -72, -63,  93,  82,  62, -44,  83, -91,  22],
       [-90, -75, -15,  67,  28,  94, -17,  38, -28, -89]])

In [53]:
vectors [2, 2:5]

array([-15,  67,  28])

## Solution of b)

In [54]:
vectors.reshape((10,3)) #  be careful, this is taking the first three values of x, then the values 4-6, etc...

array([[ 52, -76, -13],
       [-85, -75,  25],
       [-52, -98, -86],
       [-88,  -9, -72],
       [-63,  93,  82],
       [ 62, -44,  83],
       [-91,  22, -90],
       [-75, -15,  67],
       [ 28,  94, -17],
       [ 38, -28, -89]])

In [55]:
np.transpose(vectors)
vectors.T

array([[ 52,  -9, -90],
       [-76, -72, -75],
       [-13, -63, -15],
       [-85,  93,  67],
       [-75,  82,  28],
       [ 25,  62,  94],
       [-52, -44, -17],
       [-98,  83,  38],
       [-86, -91, -28],
       [-88,  22, -89]])

ASIDE: How does it zork for a 3D array (tensor) ?

In [40]:
vectors = np.random.randint(-100, 100, (3,10,2))

In [43]:
vectors.shape

(3, 10, 2)

In [44]:
vectors.T.shape

(2, 10, 3)

In [45]:
vectors.T.T.shape

(3, 10, 2)

In [50]:
np.transpose(vectors, axes=(1,0,2)).shape

(10, 3, 2)

## Part c)

In [56]:
vectors.T

array([[ 52,  -9, -90],
       [-76, -72, -75],
       [-13, -63, -15],
       [-85,  93,  67],
       [-75,  82,  28],
       [ 25,  62,  94],
       [-52, -44, -17],
       [-98,  83,  38],
       [-86, -91, -28],
       [-88,  22, -89]])

In [63]:
v0 = np.array([-1, -1, -1])

In [64]:
vectors.T + v0

array([[ 51, -10, -91],
       [-77, -73, -76],
       [-14, -64, -16],
       [-86,  92,  66],
       [-76,  81,  27],
       [ 24,  61,  93],
       [-53, -45, -18],
       [-99,  82,  37],
       [-87, -92, -29],
       [-89,  21, -90]])

In [66]:
vectors.T -1 # also works but only ecause the translationnreauested had -1 for all three components

array([[ 51, -10, -91],
       [-77, -73, -76],
       [-14, -64, -16],
       [-86,  92,  66],
       [-76,  81,  27],
       [ 24,  61,  93],
       [-53, -45, -18],
       [-99,  82,  37],
       [-87, -92, -29],
       [-89,  21, -90]])

## Part d)

In [74]:
dist=np.sum(vectors.T**2, axis=1)**0.5

In [77]:
mean_distance=np.average(dist)

In [79]:
np.mean(dist)

113.13276301108922

In [82]:
mask = dist < mean_distance

In [88]:
mask

array([ True, False,  True, False, False, False,  True, False, False,
       False])

In [83]:
mask.shape

(10,)

In [84]:
vectors.shape

(3, 10)

In [87]:
vectors.T.shape

(10, 3)

In [86]:
vectors.T[mask]

array([[ 52,  -9, -90],
       [-13, -63, -15],
       [-52, -44, -17]])

In [89]:
mask

array([ True, False,  True, False, False, False,  True, False, False,
       False])

In [90]:
np.logical_not(mask)

array([False,  True, False,  True,  True,  True, False,  True,  True,
        True])

In [91]:
~mask

array([False,  True, False,  True,  True,  True, False,  True,  True,
        True])