In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4]


In [8]:
l1, l2 = [1, 2, 3], [4, 5, 6]
print(l1+l2)
print(l1*2)
print(l1[2:])

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]
[3]


In [9]:
a1, a2 = np.array([1, 2, 3]), np.array([4, 5, 6])
print(a1+a2)
print(a1*2)
print(a1[2:])

[5 7 9]
[2 4 6]
[3]


In [12]:
print(l1[[0, 2]])

TypeError: list indices must be integers or slices, not list

In [13]:
print(a1[[0, 2]])

[1 3]


In [14]:
idx = [[0, 0],[1, 0], [2, 1]]

In [15]:
print(a[idx])

[[1 1]
 [2 1]
 [3 2]]


In [16]:
idx = np.arange(0, 100).reshape(50, 2)
print(idx)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]
 [50 51]
 [52 53]
 [54 55]
 [56 57]
 [58 59]
 [60 61]
 [62 63]
 [64 65]
 [66 67]
 [68 69]
 [70 71]
 [72 73]
 [74 75]
 [76 77]
 [78 79]
 [80 81]
 [82 83]
 [84 85]
 [86 87]
 [88 89]
 [90 91]
 [92 93]
 [94 95]
 [96 97]
 [98 99]]


In [17]:
# Create a list
l1 = [1, 2, 3]

# Getting a copy and modifying it
l2 = l1
l2[1] = 10

# Print the two lists : both are modified
print(f'l1={l1}, l2={l2}')

l1=[1, 10, 3], l2=[1, 10, 3]


In [18]:
import copy
l1 = [1, 2, 3]
l2 = copy.copy(l1)
l2[1] = 10
print(f'l1={l1}, l2={l2}')

l1=[1, 2, 3], l2=[1, 10, 3]


In [19]:
# This work with a copy
l1 = [[1, 2], [3, 4], [5, 6]]
l2 = copy.copy(l1)
l2[1] = 3
print(f'l1={l1}, l2={l2}')

l1=[[1, 2], [3, 4], [5, 6]], l2=[[1, 2], 3, [5, 6]]


In [20]:
l1 = [[1, 2], [3, 4], [5, 6]]
l2 = copy.copy(l1)
l2[1][1] = 10
print(f'l1={l1}, l2={l2}')

l1=[[1, 2], [3, 10], [5, 6]], l2=[[1, 2], [3, 10], [5, 6]]


In [21]:
# Using deepcopy() and modifying the most inner list:
l1 = [[1, 2], [3, 4], [5, 6]]
l2 = copy.deepcopy(l1)
l2[1][0] = 10
print(f'l1={l1}, l2={l2}')

l1=[[1, 2], [3, 4], [5, 6]], l2=[[1, 2], [10, 4], [5, 6]]


In [22]:
# Using deepcopy() and modifying the most inner list:
l1 = [[1, 2], [3, 4], [5, 6]]
l2 = copy.deepcopy(l1)
l2[1] = 10
print(f'l1={l1}, l2={l2}')

l1=[[1, 2], [3, 4], [5, 6]], l2=[[1, 2], 10, [5, 6]]


In [23]:
points = np.array([[ 0,  1, 2],
                   [ 3,  4, 5]])

print('a.dtype = {}'.format(points.dtype))
print('a.shape = {}'.format(points.shape))
print('a.size  = {}'.format(points.size))
print('a.ndim  = {}'.format(points.ndim))

a.dtype = int64
a.shape = (2, 3)
a.size  = 6
a.ndim  = 2


In [24]:
a = np.random.randint(low=1, high=100, size=100000)

def explicit_loop_for_inverse(array):
    res = []
    for a in array:
        res.append(1./a)
    return np.array(res)

In [25]:
%timeit explicit_loop_for_inverse(a)

62.2 ms ± 115 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
%timeit 1/a

61.8 μs ± 376 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [27]:
# Using list comprehension
%timeit [1./x for x in a]

56.5 ms ± 224 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
a = np.random.randint(low=1, high=100, size=3)
print('a        : {}'.format(a))
print('a^2      : {}'.format(a**2))
print('a/(1-a^a): {}'.format(a/(1-a**a)))
print('cos(a)   : {}'.format(np.cos(a)))
print('exp(a)   : {}'.format(np.exp(a)))

a        : [75 78 20]
a^2      : [5625 6084  400]
a/(1-a^a): [-3.07938233e-17  7.80000000e+01  9.51729109e-18]
cos(a)   : [ 0.92175127 -0.85780309  0.40808206]
exp(a)   : [3.73324200e+32 7.49841700e+33 4.85165195e+08]


In [29]:
a = np.random.randint(low=1, high=100, size=100000)

In [30]:
%timeit sum(a)

3.04 ms ± 30.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
%timeit np.sum(a)

10 μs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [32]:
# Generate 5 vectors (x,y,z)
positions = np.random.randint(low=1, high=100, size=(5, 3))

print(positions)

[[60 28 31]
 [90 13 74]
 [73 47  2]
 [24 39 27]
 [80  3  7]]


In [34]:
distances = np.sum(positions**2, axis=1)**0.5
print(distances)

[ 73.10950691 117.23907199  86.84468896  53.16013544  80.36168241]


In [35]:
a = np.random.randint(low=1, high=100, size=10)
print('a = {}'.format(a))
print('a[2] = {}'.format(a[2]))
print('a[-1] = {}'.format(a[-1]))
print('a[[1, 2, 5]] = {}'.format(a[[1, 2, 5]]))

a = [82 12 60 86 42 93 81 74 21 74]
a[2] = 60
a[-1] = 74
a[[1, 2, 5]] = [12 60 93]


In [36]:
# Small n-dimensional indices array: 3 arrays of 2 elements
indices = np.arange(6).reshape(3,2)
print('indices =\n {}'.format(indices))
print('a[indices] =\n {}'.format(a[indices]))

indices =
 [[0 1]
 [2 3]
 [4 5]]
a[indices] =
 [[82 12]
 [60 86]
 [42 93]]


In [37]:
a = np.random.randint(low=0, high=100, size=(5, 2, 3))
print('a = \n{}'.format(a))

a = 
[[[27 68 81]
  [43 14 12]]

 [[52 76 25]
  [98 51 96]]

 [[96 32 76]
  [14 18 90]]

 [[41 73 86]
  [54 38 50]]

 [[75 46 68]
  [21 22 43]]]


In [39]:
# Option 1: simple case w/ same masses
b = 1/2 * np.sum(a, axis=1)
print(b.shape)

(5, 3)


In [42]:
# Option 2: general case w/ different masses
# The generated error will be solved after 
# discussing broadcasting
ms = np.array([10, 2])
b = 1/ms.sum() * np.sum(a*ms, axis=1)
print(b.shape)

ValueError: operands could not be broadcast together with shapes (5,2,3) (2,) 

In [45]:
# Option 2: general case w/ different masses
# without broadcasting
m1, m2 = 10, 2
b = (m1*a[:, 0, :] + m2*a[:, 1, :]) / (m1+m2)
print(b)

[[29.66666667 59.         69.5       ]
 [59.66666667 71.83333333 36.83333333]
 [82.33333333 29.66666667 78.33333333]
 [43.16666667 67.16666667 80.        ]
 [66.         42.         63.83333333]]


In [44]:
# Relative distance between objects
distances = np.sum( (a[:, 0, :] - a[:, 1, :])**2, axis=1 )**0.5
print(distances)

[89.06739022 88.21564487 84.35638684 51.86520992 64.16385275]


In [46]:
# Reverse in time the data
a_rev = a[::-1]
print(a_rev)

[[[75 46 68]
  [21 22 43]]

 [[41 73 86]
  [54 38 50]]

 [[96 32 76]
  [14 18 90]]

 [[52 76 25]
  [98 51 96]]

 [[27 68 81]
  [43 14 12]]]


In [53]:
# Seed of each system: v1= dr1/dt and same for system 2,
# assuming dt between two obs is 1ms
# NO EXTERNAL tools allowed - just use numpy
velocities = (a[1:, ...] - a[:-1, ...]) / 1e-3
print(velocities.shape)

(4, 2, 3)


In [52]:
print(a[..., 0])

[[27 43]
 [52 98]
 [96 14]
 [41 54]
 [75 21]]


In [54]:
a = np.random.randint(low=-100, high=100, size=(5, 3))
mask = a>0
print('a = \n{}'.format(a))
print('\nmask = \n {}'.format(mask))

a = 
[[ -6   8  78]
 [-50 -58 -40]
 [-14 -52 -59]
 [-95  94 -80]
 [ 21 -84   3]]

mask = 
 [[False  True  True]
 [False False False]
 [False False False]
 [False  True False]
 [ True False  True]]


In [55]:
a[mask] = a[mask]**2
print(a)

[[  -6   64 6084]
 [ -50  -58  -40]
 [ -14  -52  -59]
 [ -95 8836  -80]
 [ 441  -84    9]]


In [57]:
a[mask]

array([  64, 6084, 8836,  441,    9])

In [58]:
a*mask

array([[   0,   64, 6084],
       [   0,    0,    0],
       [   0,    0,    0],
       [   0, 8836,    0],
       [ 441,    0,    9]])

In [59]:
~mask

array([[ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [False,  True, False]])

In [60]:
# Translating 3 2D vectors by d0=(1,4)
points = np.random.normal(size=(3, 2))
d0 = np.array([1, 4])
print('points:\n {}\n'.format(points))
print('points+d0:\n {}'.format(points+d0))

points:
 [[-0.66056538  0.33515651]
 [ 2.24836945 -1.75934133]
 [-0.42711169  0.03474087]]

points+d0:
 [[0.33943462 4.33515651]
 [3.24836945 2.24065867]
 [0.57288831 4.03474087]]


In [62]:
a = np.arange(10).reshape(2,5)
b = np.array([10, 20])
a+b

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [66]:
print(b[:,np.newaxis].shape)
print(b.shape)

(2, 1)
(2,)


In [67]:
a+b[:,np.newaxis]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [68]:
print(b[:,np.newaxis])

[[10]
 [20]]


In [70]:
a = np.random.randint(low=0, high=100, size=(5, 2, 3))
ms = np.array([10, 2])
b = 1/ms.sum() * np.sum(a*ms, axis=1)
print(b.shape)

ValueError: operands could not be broadcast together with shapes (5,2,3) (2,) 

In [75]:
ms = np.array([10, 2])
ms1 = ms[np.newaxis, :, np.newaxis ]
ms2 = ms[:, np.newaxis ]
b1 = 1/ms1.sum() * np.sum(a*ms1, axis=1)
b2 = 1/ms2.sum() * np.sum(a*ms2, axis=1)
print(b1.shape, b2.shape)

(5, 3) (5, 3)
